<Window x:Class="convert.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:convert"
        mc:Ignorable="d"
        Title="Microsoft Conversation Tool - www.msgang.com" ResizeMode="NoResize" WindowStartupLocation="CenterScreen" Icon="https://msgang.com/wp-content/uploads/2025/07/images.png" Width="1065" Height="500">
    <Grid Width="1045" Height="480" VerticalAlignment="Top">
        <GroupBox x:Name="groupBoxMicrosoftOffice" Header="Select a edition to conversion:" FontFamily="Consolas" FontSize="11" Width="1025" Height="440" VerticalAlignment="Top" Margin="0,10,0,0" BorderBrush="#FF164A69">
            <Canvas HorizontalAlignment="Left">
                <Rectangle Height="106" Stroke="#FF1B0F0F" Width="135" UseLayoutRounding="True" RadiusX="5" RadiusY="5" Canvas.Left="11" Canvas.Top="20" HorizontalAlignment="Center" VerticalAlignment="Top"/>
                <Label x:Name="Label2025" Content="SERVER 2025" FontWeight="Bold" Canvas.Left="11" Background="#FF1B0F0F" HorizontalAlignment="Left" VerticalAlignment="Center" Canvas.Top="8" Foreground="White" Padding="8,4,8,4"/>
                <RadioButton x:Name="radioButton2025Standard" Content="Standard " Canvas.Left="19" Canvas.Top="35" HorizontalAlignment="Left" VerticalAlignment="Top" VerticalContentAlignment="Center" Margin="0,5,0,0"/>
                <RadioButton x:Name="radioButton2025Datacenter" Content="Datacenter" Canvas.Left="19" Canvas.Top="54" HorizontalAlignment="Left" VerticalAlignment="Center" HorizontalContentAlignment="Center" VerticalContentAlignment="Center" Margin="0,5,0,0"/>
                <RadioButton x:Name="radioButton2025StandardEval" Content="Standard Eval" Canvas.Left="19" Canvas.Top="73" HorizontalAlignment="Left" VerticalAlignment="Top" VerticalContentAlignment="Center" Margin="0,5,0,0"/>
                <RadioButton x:Name="radioButton2025DatacenterEval" Content="Datacenter Eval" Canvas.Left="19" Canvas.Top="99" VerticalContentAlignment="Center" HorizontalAlignment="Center" VerticalAlignment="Top"/>
                <Rectangle Height="106" Stroke="#FF1B0F0F" Width="150" UseLayoutRounding="True" RadiusX="5" RadiusY="5" Canvas.Top="20" HorizontalAlignment="Center" Canvas.Left="156" VerticalAlignment="Top"/>
                <Label x:Name="Label2022" Content="SERVER 2022" FontWeight="Bold" Background="#FF1B0F0F" Foreground="White" Padding="8,4,8,4" Canvas.Left="156" HorizontalAlignment="Left" Canvas.Top="8" VerticalAlignment="Center"/>
                <RadioButton VerticalContentAlignment="Center" x:Name="radioButton2022Standard" Content="Standard " Canvas.Top="39" Canvas.Left="168" HorizontalAlignment="Left" VerticalAlignment="Center"/>
                <RadioButton VerticalContentAlignment="Center" Padding="5,5,5,5" x:Name="radioButton2022Datacenter" IsChecked="False" Content="Datacenter " Canvas.Top="53" Canvas.Left="168" HorizontalAlignment="Left" VerticalAlignment="Center"/>
                <RadioButton VerticalContentAlignment="Center" Padding="5,5,5,5" x:Name="radioButton2022StandardEval" IsChecked="False" Content="Standard Eval" Canvas.Top="74" Canvas.Left="168" HorizontalAlignment="Left" VerticalAlignment="Center"/>
                <RadioButton VerticalContentAlignment="Center" Padding="5,5,5,5" x:Name="radioButton2022DatacenterEval" IsChecked="False" Content="Datacenter Eval" Canvas.Top="92" Canvas.Left="168" HorizontalAlignment="Left" VerticalAlignment="Center"/>
                <Rectangle Height="106" Stroke="#FF1B0F0F" Width="150" UseLayoutRounding="True" RadiusX="5" RadiusY="5" Canvas.Left="319" Canvas.Top="20" HorizontalAlignment="Left" VerticalAlignment="Top"/>
                <Label x:Name="Label2019" Content="SERVER 2019" FontWeight="Bold" Canvas.Left="319" Canvas.Top="8" HorizontalAlignment="Left" VerticalAlignment="Center" Foreground="White" UseLayoutRounding="True" Padding="8,4,8,4" ScrollViewer.CanContentScroll="True" Background="#FF1B0F0F"/>
                <RadioButton x:Name="radioButton2019Standard" Content="Standard " VerticalContentAlignment="Center" HorizontalAlignment="Left" VerticalAlignment="Top" Canvas.Left="172" Canvas.Top="35" Margin="160,5,0,0"/>
                <RadioButton x:Name="radioButton2019Datacenter" Content="Datacenter " VerticalContentAlignment="Center" IsChecked="False" Padding="5,5,5,5" Canvas.Left="172" Canvas.Top="50" HorizontalAlignment="Left" VerticalAlignment="Center" Margin="160,5,0,0"/>
                <RadioButton x:Name="radioButton2019StandardEval" Content="Standard Eval" VerticalContentAlignment="Center" IsChecked="False" Padding="5,5,5,5" Canvas.Left="172" Canvas.Top="69" HorizontalAlignment="Left" VerticalAlignment="Top" Margin="160,5,0,0"/>
                <RadioButton x:Name="radioButton2019DatacenterEval" Content="Datacenter Eval" VerticalContentAlignment="Center" IsChecked="False" Padding="5,5,5,5" Canvas.Left="172" Canvas.Top="87" HorizontalAlignment="Left" VerticalAlignment="Top" Margin="160,5,0,0"/>
                <Rectangle Height="107" Stroke="#FF1B0F0F" Width="150" UseLayoutRounding="True" RadiusX="5" RadiusY="5" Canvas.Left="485" Canvas.Top="20" HorizontalAlignment="Left" VerticalAlignment="Top"/>
                <Label x:Name="Label2016" Content="SERVER 2016" FontWeight="Bold" Canvas.Left="484" Background="#FF1B0F0F" Canvas.Top="8" HorizontalAlignment="Left" VerticalAlignment="Center" Foreground="White" Padding="8,4,8,4"/>
                <RadioButton x:Name="radioButton2016Standard" Content="Standard " IsChecked="False" Padding="5,5,5,5" Canvas.Left="493" Canvas.Top="35" VerticalContentAlignment="Center" VerticalAlignment="Center" HorizontalAlignment="Left"/>
                <RadioButton x:Name="radioButton2016Datacenter" Content="Datacenter " VerticalContentAlignment="Center" IsChecked="False" Padding="5,5,5,5" Canvas.Left="493" Canvas.Top="55" VerticalAlignment="Center" HorizontalAlignment="Left"/>
                <RadioButton x:Name="radioButton2016StandardEval" Content="Standard Eval" VerticalContentAlignment="Center" IsChecked="False" Padding="5,5,5,5" Canvas.Left="493" Canvas.Top="75" HorizontalAlignment="Left" VerticalAlignment="Center"/>
                <RadioButton x:Name="radioButton2016DatacenterEval" Content="Datacenter Eval" VerticalContentAlignment="Center" IsChecked="False" Padding="5,5,5,5" Canvas.Left="493" Canvas.Top="95" HorizontalAlignment="Left" VerticalAlignment="Center"/>
                <Rectangle Height="290" Stroke="#FF1B0F0F" Width="172" UseLayoutRounding="True" RadiusX="5" RadiusY="5" Canvas.Left="650" Canvas.Top="20" HorizontalAlignment="Center" VerticalAlignment="Top"/>
                <Label x:Name="Label10" Content="WINDOWS 10" FontWeight="Bold" Canvas.Left="650" Background="#FF1B0F0F" Canvas.Top="8" HorizontalAlignment="Left" VerticalAlignment="Center" Padding="8,4,8,4" Foreground="White"/>
                <RadioButton x:Name="radioButton10Home" Content="Home" IsChecked="False" Padding="5,5,5,5" VerticalContentAlignment="Center" Canvas.Left="498" Canvas.Top="30" HorizontalAlignment="Center" VerticalAlignment="Center" Margin="160,5,0,0"/>
                <RadioButton x:Name="radioButton10HomeN" Content="Home N" VerticalContentAlignment="Center" IsChecked="False" Padding="5,5,5,5" Canvas.Top="50" Canvas.Left="498" HorizontalAlignment="Center" VerticalAlignment="Center" Margin="160,5,0,0"/>
                <RadioButton x:Name="radioButton10HomeSL" Content="Home SL" VerticalContentAlignment="Center" IsChecked="False" Padding="5,5,5,5" Canvas.Top="70" Canvas.Left="498" HorizontalAlignment="Center" VerticalAlignment="Center" Margin="160,5,0,0"/>
                <RadioButton x:Name="radioButton10Education" Content="Education " VerticalContentAlignment="Center" IsChecked="False" Padding="5,5,5,5" Canvas.Top="90" Canvas.Left="498" HorizontalAlignment="Center" VerticalAlignment="Center" Margin="160,5,0,0"/>
                <RadioButton x:Name="radioButton10EducationN" Content="Education N" VerticalContentAlignment="Center" IsChecked="False" Padding="5,5,5,5" Canvas.Top="110" Canvas.Left="498" HorizontalAlignment="Center" VerticalAlignment="Center" Margin="160,5,0,0"/>
                <RadioButton x:Name="radioButton10Enterprise" Content="Enterprise " VerticalContentAlignment="Center" IsChecked="False" Padding="5,5,5,5" Canvas.Top="130" Canvas.Left="498" HorizontalAlignment="Center" VerticalAlignment="Center" Margin="160,5,0,0"/>
                <RadioButton x:Name="radioButton10EnterpriseN" Content="Enterprise N" VerticalContentAlignment="Center" IsChecked="False" Padding="5,5,5,5" Canvas.Top="150" Canvas.Left="498" HorizontalAlignment="Center" VerticalAlignment="Center" Margin="160,5,0,0"/>
                <RadioButton x:Name="radioButton10Professional" Content="Professional" VerticalContentAlignment="Center" IsChecked="False" Padding="5,5,5,5" Canvas.Top="170" Canvas.Left="498" HorizontalAlignment="Center" VerticalAlignment="Center" Margin="160,5,0,0"/>
                <RadioButton x:Name="radioButton10ProfessionalN" Content="Professional N" VerticalContentAlignment="Center" IsChecked="False" Padding="5,5,5,5" Canvas.Top="190" Canvas.Left="498" HorizontalAlignment="Center" VerticalAlignment="Center" Margin="160,5,0,0"/>
                <RadioButton x:Name="radioButton10ProfessionalEducation" Content="Pro Education" VerticalContentAlignment="Center" IsChecked="False" Padding="5,5,5,5" Canvas.Top="214" Canvas.Left="658" HorizontalAlignment="Center" VerticalAlignment="Top"/>
                <RadioButton x:Name="radioButton10ProfessionalEducationN" Content="Pro Education N" VerticalContentAlignment="Center" IsChecked="False" Padding="5,5,5,5" Canvas.Top="230" Canvas.Left="498" HorizontalAlignment="Center" VerticalAlignment="Center" Margin="160,5,0,0"/>
                <RadioButton x:Name="radioButton10ProfessionalWorkstation" Content="Pro for Workstation" VerticalContentAlignment="Center" IsChecked="False" Padding="5,5,5,5" Canvas.Top="250" Canvas.Left="498" HorizontalAlignment="Center" VerticalAlignment="Center" Margin="160,5,0,0"/>
                <RadioButton x:Name="radioButton10ProfessionalWorkstationN" VerticalContentAlignment="Center" IsChecked="False" Padding="5,5,5,5" Content="Pro for Workstation N" Canvas.Top="270" Canvas.Left="498" HorizontalAlignment="Center" VerticalAlignment="Center" Margin="160,5,0,0"/>
                <Rectangle Height="290" Stroke="#FF1B0F0F" Width="172" UseLayoutRounding="True" RadiusX="5" RadiusY="5" Canvas.Left="835" Canvas.Top="20" VerticalAlignment="Top"/>
                <Label x:Name="Label11" Content="WINDOWS 11" FontWeight="Bold" Canvas.Left="835" Background="#FF1B0F0F" Canvas.Top="8" VerticalAlignment="Center" Foreground="White" Padding="8,4,8,4" HorizontalAlignment="Left" BorderThickness="1,1,1,1"/>
                <RadioButton x:Name="radioButton11Home" Content="Home" IsChecked="False" Padding="5,5,5,5" VerticalContentAlignment="Center" Canvas.Left="844" Canvas.Top="35" VerticalAlignment="Center" HorizontalAlignment="Left"/>
                <RadioButton x:Name="radioButton11HomeN" Content="Home N" VerticalContentAlignment="Center" IsChecked="False" Padding="5,5,5,5" Canvas.Top="55" Canvas.Left="844" VerticalAlignment="Center" HorizontalAlignment="Left"/>
                <RadioButton x:Name="radioButton11HomeSL" Content="Home SL" VerticalContentAlignment="Center" IsChecked="False" Padding="5,5,5,5" Canvas.Top="75" Canvas.Left="844" VerticalAlignment="Center" HorizontalAlignment="Left"/>
                <RadioButton x:Name="radioButton11Education" Content="Education " VerticalContentAlignment="Center" IsChecked="False" Padding="5,5,5,5" Canvas.Top="95" Canvas.Left="844" VerticalAlignment="Center" HorizontalAlignment="Left"/>
                <RadioButton x:Name="radioButton11EducationN" Content="Education N" VerticalContentAlignment="Center" IsChecked="False" Padding="5,5,5,5" Canvas.Top="115" Canvas.Left="844" VerticalAlignment="Center" HorizontalAlignment="Left"/>
                <RadioButton x:Name="radioButton11Enterprise" Content="Enterprise " VerticalContentAlignment="Center" IsChecked="False" Padding="5,5,5,5" Canvas.Top="135" Canvas.Left="844" VerticalAlignment="Center" HorizontalAlignment="Left"/>
                <RadioButton x:Name="radioButton11EnterpriseN" Content="Enterprise N" VerticalContentAlignment="Center" IsChecked="False" Padding="5,5,5,5" Canvas.Top="155" Canvas.Left="844" VerticalAlignment="Center" HorizontalAlignment="Left"/>
                <RadioButton x:Name="radioButton11Professional" Content="Professional " VerticalContentAlignment="Center" IsChecked="False" Padding="5,5,5,5" Canvas.Top="175" Canvas.Left="844" VerticalAlignment="Center" HorizontalAlignment="Left"/>
                <RadioButton x:Name="radioButton11ProfessionalN" Content="Professional N" VerticalContentAlignment="Center" IsChecked="False" Padding="5,5,5,5" Canvas.Top="195" Canvas.Left="844" VerticalAlignment="Center" HorizontalAlignment="Left"/>
                <RadioButton x:Name="radioButton11ProfessionalEducation" Content="Pro Education" VerticalContentAlignment="Center" IsChecked="False" Padding="5,5,5,5" Canvas.Top="215" Canvas.Left="844" VerticalAlignment="Center" HorizontalAlignment="Left"/>
                <RadioButton x:Name="radioButton11ProfessionalEducationN" Content="Pro Education N" VerticalContentAlignment="Center" IsChecked="False" Padding="5,5,5,5" Canvas.Top="235" Canvas.Left="844" VerticalAlignment="Center" HorizontalAlignment="Left"/>
                <RadioButton x:Name="radioButton11ProfessionalWorkstation" Content="Pro for Workstation" VerticalContentAlignment="Center" IsChecked="False" Padding="5,5,5,5" Canvas.Top="255" Canvas.Left="844" VerticalAlignment="Center" HorizontalAlignment="Left"/>
                <RadioButton x:Name="radioButton11ProfessionalWorkstationN" Content="Pro for Workstation N" VerticalContentAlignment="Center" IsChecked="False" Padding="5,5,5,5" Canvas.Top="275" Canvas.Left="844" HorizontalAlignment="Left" VerticalAlignment="Center"/>
                <TextBox x:Name="textBox1" TextWrapping="Wrap" Text="(1) Select the destination edition you want to convert to." Canvas.Top="286" FontSize="10.5" BorderBrush="{x:Null}" Background="{x:Null}" HorizontalAlignment="Left" VerticalAlignment="Top" Canvas.Left="6" Padding="0,0,0,2" TextChanged="textBox1_TextChanged"/>
                <TextBox x:Name="textBox2" TextWrapping="Wrap" Text="(2) Click on the Submit button and wait for a while." Canvas.Top="310" FontSize="10.5" BorderBrush="{x:Null}" Background="{x:Null}" HorizontalAlignment="Left" VerticalAlignment="Top" Canvas.Left="6" Padding="0,0,0,2"/>
                <TextBox x:Name="textBox3" TextWrapping="Wrap" Text="(*) The tool supports convert all Windows editions." Canvas.Top="331" FontSize="10.5" BorderBrush="{x:Null}" Background="{x:Null}" HorizontalAlignment="Left" VerticalAlignment="Center" Canvas.Left="6" Padding="0,0,0,2"/>
                <TextBox x:Name="textBox4" TextWrapping="Wrap" Text="(*) Auto activate the Windows license after converting." Canvas.Top="352" FontSize="10.5" BorderBrush="{x:Null}" Background="{x:Null}" HorizontalAlignment="Left" VerticalAlignment="Top" Canvas.Left="6" Padding="0,0,0,2"/>
                <TextBox x:Name="textBox5" TextWrapping="Wrap" Text="(*) More FREE Microsoft products, please visit:" Canvas.Top="373" FontSize="10.5" BorderBrush="{x:Null}" Background="{x:Null}" Canvas.Left="6" HorizontalAlignment="Left" VerticalAlignment="Top" Padding="0,0,0,2"/>
                <Image x:Name="image" Height="81" Width="78" Canvas.Left="151" Canvas.Top="142" Source="https://raw.githubusercontent.com/msgang822/microsoft/refs/heads/main/files/office/donate.png" HorizontalAlignment="Left" VerticalAlignment="Center" Visibility="Hidden"/>
            </Canvas>
        </GroupBox>
        <Button x:Name="buttonSubmit" Content="Submit" HorizontalAlignment="Left" Margin="147,212,0,0" VerticalAlignment="Top" Width="118" Height="28" Background="#FF168E12" Foreground="White" FontFamily="Consolas" FontSize="13" FontWeight="Bold" UseLayoutRounding="True" BorderBrush="#FF168E12"/>
        <ProgressBar x:Name="progressbar" HorizontalAlignment="Left" Height="10" Margin="147,252,0,0" VerticalAlignment="Top" Width="118" IsEnabled="False" Background="{x:Null}" BorderBrush="{x:Null}"/>
        <TextBox x:Name="textbox" TextWrapping="Wrap" Width="339" HorizontalAlignment="Left" VerticalAlignment="Top" Margin="42,277,0,0" FontFamily="Consolas" FontSize="11" HorizontalContentAlignment="Center" VerticalContentAlignment="Center" Background="{x:Null}" BorderBrush="{x:Null}" AllowDrop="False" Focusable="False" IsHitTestVisible="False" IsTabStop="False" IsUndoEnabled="False"/>
        <Label x:Name="Link1" HorizontalAlignment="Left" Margin="303,392,0,0" VerticalAlignment="Top" Width="120" FontSize='10.5' ToolTip='vmware' FontFamily="Consolas" Padding="5,5,5,2">
            <Hyperlink NavigateUri="https://msgang.com">https://msgang.com</Hyperlink>
        </Label>

    </Grid>
</Window>
